### ISSUE TITLE
Pre-built binaries?

### ISSUE THREAD

**Issue by aninusmuffin** [NerdyPuzzle/MCreator-Fabric-Generator-1.18.2#1]
> The current targeted Minecraft version is 1.18.2. Installation Instructions Pre-built binaries can be found on the Release page of this repository.

Are there Pre-built binaries?

**Comment by aninusmuffin** [comment]
Sorry, I found the [mcreator page](https://mcreator.net/plugin/91685/fabric-generator-1182).

**Comment by NerdyPuzzle** [comment]
I just copy pasted the text of the original generator.
